### ISSUE TITLE
XMLNode.indexIsValid method - is it correct ? 

### ISSUE THREAD

**Issue by ivrusuboca** [craiggrummitt/SwiftXML#2]
Hi Graig,

I was wondering , shouldn't XMLNode method indexIsValid be using 'index < children.count' - that is, strictly less operator - rather than index <= children.count ? 

Thanks. Ionut.

**Comment by craiggrummitt** [comment]
Thanks, you're right!
https://github.com/craiggrummitt/SwiftXML/commit/fb92a5f3521d5a98b8601782e0cf1b81734a6181

**Comment by ivrusuboca** [comment]
Thank you.
