### ISSUE TITLE
The modifications done are not effecting the xml file

### ISSUE THREAD

**Issue by SireeshaSiddineni** [craiggrummitt/SwiftXML#5]
The modified xml is printing but not effecting the file that is existing in the project

**Comment by craiggrummitt** [comment]
This is working as expected. This framework is set up to instantiate an `XML` object(a custom class) by 'importing' XML from a source, which can be either a URL or a data object.

Any subsequent modifications to the `XML` object do not affect the source (i.e. either URL or data object). You can, however, regenerate the `XML` object to an XML structure, with the `description` property. If you wanted to then update the original source file, you could then overwrite the source file with this description.
